### PR TITLE
Added sub question for question #5

### PR DESCRIPTION
**Pull request by KromDaniel**
There are some Javascript tricks when writing custom `toString` method, I found it worth to mention at the questions.

I added this at the `closure` section

### Mul V2 Question - Write function that works for all the next cases:

```javascript
// notice the `
console.log(`${mul(3)(2)(3)(12)(64)}`);
console.log(`${mul(3)(2)(3)(12)(64)(98)(12)}`);
console.log(`${mul(1)(2)(3)(4)(5)(6)(7)(8)(8)(10)(11)(12)(13)(14)(15)(16)(17)}`);
```

With the answer

```javascript
function mul(x) {
  let res = x;
  const fn = function(n) {
    res*=n;
    return fn;
  }

  fn.toString = function() {
    return res.toString();
  }
  return fn;
}
```

### CODE REVIEW

**Comment by ganqqwerty** [comment]
weeeeeeell... I don't particularly like this solution because you never actually return the value: 
```
typeof(mul(3)(2)(3)(12)(64))
"function"
```
so your solution works for console.log because of your toSting hack, but it won't be easy to use in the production code. Here's how I guess you will need to proceed if you want to use the `mul` function in the big project:

```
parseFloat(mul(3)(2)(3)(12)(64).toString())
```

Not very elegant in terms of types. Can your propose another solution where the return type of mul will be `number`?

**Comment by KromDaniel** [comment]
Sorry for the delay
We can implement it with `Proxy` traps but then it shouldn't be under the closures section :)

**Comment by ganqqwerty** [comment]
If you can provide proxy implementation I will be delighted to include it in the book

**Comment by KromDaniel** [comment]
Sorry for the delay, sure I'll

**Comment by ganqqwerty** [comment]
close due to inactivity. Could be reopened in the future

**Pull request closed without merging**
